//
//  AmazonItemDB.swift
//  NC1_Amazon_Mobile
//
//  Created by Francesco De Stasio on 21/11/22.
//

import Foundation



var AmazonItemsDBAmazon : [AmazonSeleableItem] = [
    
    AmazonSeleableItem(name: "Echo dot 3° Generation", description: "Introducing the Echo Dot - Our best-selling smart speaker, with a fabric finish that fits perfectly into even the smallest spaces.Control music with your voice - Stream songs from Amazon Music, Apple Music, Spotify, TuneIn and other music services. With Audible, you can also listen to your favorite audiobooks.Richer, more powerful sound - Pair with another Echo Dot (3rd generation) for powerful stereo sound. To fill your home with music, you can use multiple compatible Echo devices in different rooms.Always ready to help - Ask Alexa to play music, answer questions, read you the latest news, give you the weather forecast, set alarms, control compatible smart home devices and much more.Always stay in touch with others - Call and send hands-free messages to anyone with an Echo device, the Alexa app or Skype. With the Drop In feature, you can also instantly call a compatible Echo device that's in another room. Customize Alexa with Skills - With hundreds of Skills available, Alexa is getting smarter and new features and Skills are being added all the time. Use them to track your workouts, play games and more.Control smart home devices with your voice - Use your voice to turn on lights, adjust a thermostat, and control other compatible devices. Designed to protect your privacy - Echo was designed with several elements to protect and control privacy, including a microphone mute button.", price: 17.99, images: ["echo_dot1", "echo_dot2", "echo_dot3"], features: ["Size" : "43 x 99 x 99 mm", "Weight":"300 grams. Actual size and weight may vary by manufacturing process", "Wi-Fi Connectivity": "Dual-band Wi-Fi supports 802.11 a/b/g/n (2.4 and 5 GHz) networks. Does not support connecting to ad-hoc (or peer-to-peer) Wi-Fi networks. WiFi 6 (802.11ax) is not currently supported."]),
                                
    AmazonSeleableItem(name: "2021 Apple MacBook Pro (14-inch, Apple M1 Pro chip with 8‑core CPU and 14‑core GPU, 16GB RAM, 512GB SSD) - Space Grey", description: " Apple M1 Pro or M1 Max chip for a massive leap in CPU, GPU and machine learning performance. Up to 10-core CPU delivers up to 3.7x faster performance to fly through pro workflows quicker than ever. Up to 32-core GPU with up to 13x faster performance for graphics-intensive apps and games. 16-core Neural Engine for up to 11x faster machine learning performance. Longer battery life, up to 17 hours. Up to 64GB of unified memory so everything you do is fast and fluid. Up to 8TB of superfast SSD storage launches apps and opens files in an instant. Stunning 14-inch Liquid Retina XDR display with extreme dynamic range and contrast ratio. 1080p FaceTime HD camera with advanced image signal processor for sharper video calls. Six-speaker sound system with force-cancelling woofers", price: 2069.00, images: ["macbook1","macbook2","macbook3"], features: ["Brand":"Apple", "Model name": "MacBook Pro", "Screen size": "14 Inches", "Colour": "Space Gray", "CPU model ": " A Series", "RAM memory installed size ": "16 GB", "CPU speed ": "3.1 GHz"]),
    
    AmazonSeleableItem(name: "AKAI Professional MPK Mini– 25 Key USB MIDI Keyboard Controller with 8 Backlit Drum Pads, 8 Knobs and Music Production Software Included", description: "Music Production and Beat Maker Essential – USB powered MIDI controller with 25 mini MIDI keyboard velocity-sensitive keys for studio production, virtual synthesiser control and beat production. Total Control of your Production - Innovative Four-way thumbstick for dynamic pitch and modulation control, plus a built-in arpeggiator with adjustable resolution, range and modes. The MPC Experience - Eight backlit velocity-sensitive MPC-style MIDI beat pads with Note Repeat and Full Level for programming drums, triggering samples and controlling virtual synth / DAW controls. Complete Command of your Virtual Instruments and FX - 8 360-degree knobs assign to all your music studio plugins for mixing, tweaking synth controls and more. 1500+ Sounds and Everything You Need for Pro Production – Complete music production starter Kit including MPC Beats, six Virtual Instruments and 2GB of sound content.", price: 79.00, images: ["akai1", "akai2", "akai3", "akai4", "akai5"], features: ["Product Dimensions ": "18.11 x 31.75 x 4.45 cm; 900 Grams", "Item model number ": "MPKMINI3", "Colour ": "Standard 25 keys", "Hardware Interface ": "USB", "Number of Keyboard Keys ": "25", "Item Weight ": "900 g"]),
    
    AmazonSeleableItem(name: "Modern Lounge Padded Chair Dining Chair with Metal Legs Living Room Chair Lumbar Support Fabric Leisure Bedroom Study Desk Task Chair with Armrests (Yellow)", description: "[Modern Simple Fabric Design]: The seat of Padded Armchair is featured by Non-fabric and high resilience sponge, which is soft and breathable and kicks the sticky feeling away from us.More suitable for your sitting posture, provide you comfortable relaxing at home lounge Bedroom or office. [Soft Padded and Cushion]: The armchair is featuring a modern curved back with soft padded seat, this dining chair is so ergonomic and provide your low back and spine enough support. It's tub silhouette with armrest wraps your body up in a sleek and soft seat, makes you feel so relaxed. [Robust Bottom Construction]- The Faux wood texture coated tapered metal legs with 4 angles structure bring more stable, strong and anti-rust features to this leisure office chair. the warm color style give you a more comfortable relax. The weight capacity can be up to 250 pounds. [Foot-pads Protects Floor ]: To improve the stability, we use four foot-pads at the bottom of the desk chair, these foot-pads are helpful for protecting the floor from scratches and damages. The tiny design More concern your life. [Appropriate Size Seat of Chair]: The seat area of the chair is 44x40cm (WxD), seat height is 57cm, which is not too big or small and would be perfect for your dining room, living room, leisure area, or as a dressing table chair in your bedroom, desk chair in your home office.[Installation and After-sale Service]: We provided detailed and easy-to-understand installation instructions and presented the necessary installation tools. Any issues about installation or returns, please feel free to contact us, we will come to you ASAP.", price: 159.00, images: ["chairyellow1","chairyellow2", "chairyellow3", "chairyellow4", "chairyellow5"], features: ["Colour ": "Yellow", "Brand ": "Jiexi", "Product dimensions ": "63D x 57.9W x 79H centimetres", "Style" : "Modern", "Special feature ": "Armrest, Ergonomic, Lumbar Support", "Item Weight ": "‎9.39 kg"]),
                                                  
    
    AmazonSeleableItem(name: "Neo Crushed Velvet Shell Scallop Accent Occasional Chair Armchair Dining Furniture (Midnight Blue)", description: "Overall height 82 cm.\n Width 57 cm.\n Depth 47 cm.\n Crushed Colourful Velvet Upholstery.\n High Quality Fabric", price: 79.99, images: ["chairblue1", "chairblue2", "chairblue3", "chairblue4"], features: ["Colour ": "Midnight Blue", "Brand ": "Neo", "Product dimensions ": "47D x 57W x 82H centimetres", "Style ":"Contemporary", "Special feature ": "Solid Black Wood Legs, Crushed Velvet, Top Quality Fabric, Shell Detail"])
    
    
]


var amazonCartItems : [AmazonSeleableItem] = []
